export const FETCH_WORDS_INIT = "FETCH_WORDS_INIT";
export const FETCH_WORDS_SUCCESS = "FETCH_WORDS_SUCCESS";
export const FETCH_WORDS_FAILURE = "FETCH_WORDS_FAILURE";

export const FETCH_MEANING_INIT = "FETCH_MEANING_INIT";
export const FETCH_MEANING_SUCCESS = "FETCH_MEANING_SUCCESS";
export const FETCH_MEANING_FAILURE = "FETCH_MEANING_FAILURE";

export const FIREBASE_SIGNIN_INIT = "FIREBASE_SIGNIN_INIT";
export const FIREBASE_SIGNIN_SUCCESS = "FIREBASE_SIGNIN_SUCCESS";
export const FIREBASE_SIGNIN_FAIL = "FIREBASE_SIGNIN_FAIL";

export const FIREBASE_SIGNOUT_INIT = "FIREBASE_SIGNOUT_INIT";
export const FIREBASE_SIGNOUT_SUCCESS = "FIREBASE_SIGNOUT_SUCCESS";
export const FIREBASE_SIGNOUT_FAIL = "FIREBASE_SIGNOUT_FAIL";

export const DATABASE_GET_WORDS_INIT = "DATABASE_GET_WORDS_INIT";
export const DATABASE_GET_WORDS_SUCCESS = "DATABASE_GET_WORDS_SUCCESS";
export const DATABASE_GET_WORDS_FAIL = "DATABASE_GET_WORDS_FAIL";

export const DATABASE_STORE_WORDS_INIT = "";
